version: '3'

services:
  go-app:
    build: .
    restart: unless-stopped
    ports: [ "8080:8080" ]
    volumes:
      - .:/go/src/app
    env_file:
      - .env



  go-load:
    build: .
    restart: unless-stopped
    ports: [ "8082:8082" ]
    volumes:
      - .:/go/src/app
    env_file:
      - .env

    command: go run cmd/load/main.go


  prometheus:
    image: prom/prometheus:v2.42.0
    ports:
      - 9090:9090
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:9.3.6
    ports:
      - 3000:3000
