version: '3'

services:
  go:
    build: .
    restart: unless-stopped
    ports: [ "8080:8080" ]
    volumes:
      - .:/go/src/app
    env_file:
      - .env

    command: go run cmd/app/main.go -b 0.0.0.0

    networks:
      - local


  go-load:
    build: .
    restart: unless-stopped
    ports: [ "8081:8081" ]
    volumes:
      - .:/go/src/app
    env_file:
      - .env

    command: go run cmd/load/main.go -b 0.0.0.0

    networks:
      - local


  prometheus:
    image: prom/prometheus:v2.42.0
    ports:
      - 9090:9090
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - local

  grafana:
    image: grafana/grafana:9.3.6
    ports:
      - 3000:3000
    networks:
      - local

networks:
  local:
    driver: bridge