version: '3'

services:
  go:
    build: .
    restart: unless-stopped
    ports: [ "8080:80" ]
    volumes:
      - .:/go/src/app
    env_file:
      - .env


  prometheus:
    image: prom/prometheus:v2.42.0
    ports:
      - 9090:9090
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - local

  grafana:
    image: grafana/grafana:9.3.6
    ports:
      - 3000:3000
    networks:
      - local

networks:
  local: